version: "3.9"

services:
  problem-solving-api:
    image: costarcc/problem-solving-api:V1.00
    container_name: problem-solving-api
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - /mnt/teklog/DumpTrack:/data/DumpTrack
      - /mnt/teklog/Monitor:/data/Monitor
    restart: unless-stopped
