services:
  problem-solving-api:
    image: suyash/problem-solving-api:V1.01
    container_name: problem-solving-api
    ports:
      - "9002:9000"
    env_file:
      - .env
    volumes:
      - ${DUMPTRACK_HOST_PATH}:/data/DumpTrack:ro
      - ${MONITOR_HOST_PATH}:/data/Monitor:ro
    restart: unless-stopped
