version: "3.9"

services:
  problem-solving-api:
    container_name: problem-solving-api
    build: .
    ports:
      - "9002:9000"
    env_file:
      - .env
    volumes:
      - ${DUMPTRACK_HOST_PATH}:/data/DumpTrack:ro
      - ${MONITOR_HOST_PATH}:/data/Monitor:ro
    restart: unless-stopped
